### ISSUE TITLE
Carthageでメインターゲットに追加したライブラリはEmbedded framework側で"copy-frameworks"しなくても良い説

### ISSUE THREAD

**Issue by hryoichi** [hryoichi/ios-boilerplate#5]
- `Presentation.framework`を追加してRxSwiftを導入しようとしたら`lipo: truncated or malformed fat file`エラー
- CleanしたりDerivedDataを消してみても解決せず
- 各ターゲットで`Linked Frameworks and Libraries`の参照は残したままRun ScriptでRxSwiftを`copy-framework`している箇所を（メインターゲット以外）消したらビルドが通った
- 手元の実行環境の問題かも

**Comment by moaible** [comment]
導入手順としてはこちらをベースにしました

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

もしかするとEmbedded Frameworkに対しては設定が異なるかもしれません 🙇 

もう一度色々設定変えて見ます

**Comment by moaible** [comment]
確かにcopy-frameworkを消すとビルド問題なく通りました

**Comment by hryoichi** [comment]
firefox-iosのプロジェクト設定見た所Carthageのcopy-famework実行するRun Scriptはメインターゲットにまとめられていますね。

https://github.com/mozilla-mobile/firefox-ios
